##### 멀티 catch

자바 7부터 하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 멀티(multi) catch 기능을 추가했다. catch 괄호() 안에 동일하게 처리하고 싶은 예외를 |로 연결하면 된다.

```java
try {
} catch(ArrayIndexOutOfBoundsException | NumberFormatExcption e) {
} catch(Exception e) {
}
```



#### 자동 리소스 닫기

try-with-resources를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체(각종 입출력 스트림, 서버 소켓, 소켓, 각종 채널)의 close() 메소드를 호출해서 안전하게 리소스를 닫아준다. 리소스는 데이터를 읽고 쓰는 객체라고 생각해두자. 예를 들어 파일의 데이터를 읽는 FileInputStream 객체와 파일에 쓰는 FileOutputStream은 리소스 객체라고 보면 된다. 자바 7에서 추가된 try-with-resources를 사용하면 간단해진다.

```
try(FileInputStream fis = new FileInputStream("file.txt")) {
	...
} catch(IOException e) {
	...
}
```

try 블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하면 자동으로 FileInputStream의 close() 메소드를 호출한다. try {}에서 예외가 발생하면 우선 close()로 리소스를 닫고 catch 블록을 실행한다.

try-with-resources를 사용하기 위해서는 **리소스 객체는 java.lang.AutoCloseable 인터페이스를 구현**하고 있어야 한다. Autocloseable에는 close() 메소드가 정의되어 있는데 try-with-resoces는 close() 메소드를 자동 호출한다. 

#### 예외 떠넘기기

메소스 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다. **throws 키워드는 메소드 선언부 끝에 작성되어 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할을 한다**. throws 키워드 뒤에는 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.

```java
리턴타입 메소드명(매개변수, ...) throws 예외클래스1, 예외클래스2, ... {
}
```

예외의 종류별로 throws 뒤에 나열하는 것이 일반적이지만, throws Exception만으로 모든 예외를 간단히 떠넘길 수도 있다.

```java
리턴타입 메소드명(매개변수, ...) throws Exception {
}
```

throws 키워드가 붙어있는 메소드는 반드시 try 블록 내에서 호출되어야 한다. 그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다.

main() 메소드에서도 throws 키워드를 사용해서 예외를 떠넘길 수 있는데, 결국 JVM이 최종적으로 예외 처리를 하게 도니다. JVM은 예외의 내용은 콘솔(Console)에 출력하는 것으로 예외 처리를 한다. main() 메소드에서 throws Exception을 붙이는 것은 좋지 못한 예외 처리 방법이기에 main()에서 try-catch 블록으로 예외를 최종 처리하는 것이 바람직한다.



#### 사용자 정의 예외와 예외 발생

프로그램을 개발하다 보면 자바 표준 API에서 제공하는 예외 클래스만으로는 다양한 종류의 예외를 표현할 수가 없다. 애플리케이션 서비스와 관련된 예외를 애플리케이션 예외(Application Exception)라고 한다. 애플리케이션 예외는 개발자가 직접 정의해서 만들어야 하므로 사용자 정의 예외라고도 한다.

##### 사용자 정의 예외 클래스 선언

사용자 정의 예외 클래스는 컴파일러가 체크하는 일반 예외로 선언할 수 있고, 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다. 일반 예외로 선언할 경우 Exception을 상속하면 되고, 실행 예외로 선언할 경우에는 RuntimeException을 상속하면 된다.

```java
public class XXXException extends [ Exception | RuntimeException ] {
	public XXXException() {}
	public XXXException(Strin message) {super(message)};
}
```

사용자 정의 예외 클래스 이름은 Exception으로 끝나는 것이 좋다. 사용자 정의 예외 클래스도 필드, 생성자, 메소드 선언들을 포함할 수 있지만 대부분 생성자 선언만을 포함한다. 생성자는 매개 변수가 없는 기본 생성자, 예외 발생 원인(예외 메세지)을 전달하기 위해 String 타입의 매개 변수를 갖는 생성자이다. String 타입의 매개 변수를 갖는 생성자는 상위 클래스의 생성자를 호출하여 예외 메세지를 남겨준다. 예외 메시지의 용도는 catch {} 블록의 예외 처리 코드에서 이용하기 위해서이다.

##### 예외 발생시키기

사용자 정의 예외 또는 자바 표준 예외를 코드에서 발생시키는 방법을 알아보자.

```java
throw new XXXException();
throw new XXXException("메시지");
```

예외 발생 코드를 가지고 있는 메소드는 내부에서 try-catch 블록으로 예외를 처리할 수 있지만, 대부분은 자신이 호출하 곳에서 예외를 처리하도록 throws 키워드로 예외를 떠넘긴다.

```java
public void method() throws XXXException {
	throw new XXXException("메시지");
}
```

그렇기 때문에 throws 키워드를 포함하고 있는 메소드는 호출한 곳에서 다음과 같이 예외 처리를 해주어야 한다.

```java
try {
	method();
} catch(XXXException e) {
	// 예외 처리
}
```



#### 예외 정보 얻기

try 블록에서 예외가 발생하면 예외 객체는 catch 블록의 매개 변수에서 참조하게 되므로 매개 변수를 이용하면 예외 객체의 정보를 알 수 있다. 모든 예외 객체는 Exception 클래스를 상속하기 때문에 Exceptioon이 가지고 있는 메소드들을 모든 예외 객체에서 호출할 수 있다. 그중에서도 가장 많이 사용되는 메소드는 getMessage()와 printStackTrace()이다. 예외를 발생시킬 때 다음과 같이 String 타입의 메시지를 갖는 생서자를 이용하였다면, 메시지는 자동적으로 예외 객체 내부에 저장된다.

```java
throw new XXXException("예외 메시지");
```

예외 메시지의 내용에는 왜 예외가 발생했는지에 대한 간단한 설명이 포함된다. 좀 더 상세한 원인을 세분화하기 위해 예외 코드를 포함하기도 한다. 이와 같은 예외 메시지는 다음과 같이 catch 블록에서 getMessage() 메소드의 리턴값으로 얻을 수 있다.

```java
} catch(Exception e) {
	String message = e.getMessage();
}
```

printStackTrace()는 메소드 이름에서도 알 수 있드시 예외 발생 코드를 추적해서 모두 콘솔에 출력한다. 어떤 예외가 어디에서 발생했는지 상세하게 출력해주기 때문에 프로그램을 테스트하면서 오류를 찾을 때 활용된다.

```java
try {
} catch(예외클래스 e) {
	// 예외가 가지고 있는 Message 얻기
	String messsage = e.getMessage();
	
	// 예외의 발생 경로를 추적
	e.printStackTrace();
}
```

